# Generated by Django 5.2.11 on 2026-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_project_remove_student_enrollment_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=10)),
                ('coursename', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('enrollment', models.ManyToManyField(related_name='students', to='hello.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
