# Generated by Django 5.2.11 on 2026-05-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_course_student_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
